<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SupplierSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $suppliers = [
            [
                'user_id' => 1,
                'name' => 'ALFA QUANTUM LABORATORIOS 2010.C.A',
                'tax_id' => 'J-29898050-8',
                'contact_person' => null,
                'representative_cedula' => null,
                'email' => null,
                'phone' => '(0212) 414-22-71',
                'address' => 'AV INTERCOMUNAL DEL VALLE, CONJ RESIDENCIAL LONGARAY, URB LONGARAY CARACAS, DISTRITO CAPITAL',
                'fiscal_address' => 'AV INTERCOMUNAL DEL VALLE, CONJ RESIDENCIAL LONGARAY, URB LONGARAY CARACAS, DISTRITO CAPITAL',
                'is_active' => true,
            ],
            [
                'user_id' => 1,
                'name' => 'BIO-KERN.CA',
                'tax_id' => 'J-40495367-1',
                'contact_person' => null,
                'representative_cedula' => null,
                'email' => null,
                'phone' => '(0212) 316-64-37',
                'address' => 'Miranda, San Antonio de los Altos',
                'fiscal_address' => 'Miranda, San Antonio de los Altos',
                'is_active' => true,
            ],
            [
                'user_id' => 1,
                'name' => 'CARLOS ALFREDO ALFONZO DUARTE',
                'tax_id' => 'V-06519315-5',
                'contact_person' => 'Carlos Alfredo Alfonzo Duarte',
                'representative_cedula' => 'V-06519315-5',
                'email' => null,
                'phone' => null,
                'address' => 'URB VALLE GRANDE, SECTOR LAS PLANADAS, GUATIRE',
                'fiscal_address' => 'URB VALLE GRANDE, SECTOR LAS PLANADAS, GUATIRE',
                'is_active' => true,
            ],
            [
                'user_id' => 1,
                'name' => 'CORPORACION MEDICA DDF0105 CA',
                'tax_id' => 'J-40587017-6',
                'contact_person' => null,
                'representative_cedula' => null,
                'email' => null,
                'phone' => '(0412) 906-56-42',
                'address' => 'URB. LOS ROSALES, CARACAS, DISTRITO CAPITAL',
                'fiscal_address' => 'URB. LOS ROSALES, CARACAS, DISTRITO CAPITAL',
                'is_active' => true,
            ],
            [
                'user_id' => 1,
                'name' => 'FARMATODO',
                'tax_id' => 'J-00020200-1',
                'contact_person' => null,
                'representative_cedula' => null,
                'email' => null,
                'phone' => null,
                'address' => 'No registrada',
                'fiscal_address' => 'No registrada',
                'is_active' => true,
            ],
            [
                'user_id' => 1,
                'name' => 'FERRETERIA EL PASEO S.R.L',
                'tax_id' => 'J-00129350-7',
                'contact_person' => null,
                'representative_cedula' => null,
                'email' => null,
                'phone' => '(0212) 690-09-45',
                'address' => 'PASEO LOS ILUSTRES, ESQ EL PARQUE, EDIF. TIBET, LAS ACACIAS, CARACAS',
                'fiscal_address' => 'PASEO LOS ILUSTRES, ESQ EL PARQUE, EDIF. TIBET, LAS ACACIAS, CARACAS',
                'is_active' => true,
            ],
            [
                'user_id' => 1,
                'name' => 'FLORISTERIA PROVI',
                'tax_id' => 'J-40623298-0',
                'contact_person' => null,
                'representative_cedula' => null,
                'email' => null,
                'phone' => '(0212) 661-59-82',
                'address' => 'AV. LAS CIENCIAS, EDF MARCO, URB. LOS CHAGUARAMOS, CARACAS',
                'fiscal_address' => 'AV. LAS CIENCIAS, EDF MARCO, URB. LOS CHAGUARAMOS, CARACAS',
                'is_active' => true,
            ],
            [
                'user_id' => 1,
                'name' => 'YOHANA ALVARADO',
                'tax_id' => 'V-06320108-8',
                'contact_person' => 'Yohana Alvarado',
                'representative_cedula' => 'V-06320108-8',
                'email' => null,
                'phone' => '(0212) 564-51-10',
                'address' => 'CALLE SUCRE, QUINTA YOLA, URB. LOS MOLINOS, CARACAS-DTTO. CAPITAL',
                'fiscal_address' => 'CALLE SUCRE, QUINTA YOLA, URB. LOS MOLINOS, CARACAS-DTTO. CAPITAL',
                'is_active' => true,
            ],
            [
                'user_id' => 1,
                'name' => 'INVERSIONES DJ MULTIPARTS 2013.C.A.',
                'tax_id' => 'J-40279245-0',
                'contact_person' => null,
                'representative_cedula' => null,
                'email' => null,
                'phone' => '(0212) 661-57-62',
                'address' => 'AV. UNIVERSITARIA, EDIF. ODEON, URB. LOS CHAGUARAMOS',
                'fiscal_address' => 'AV. UNIVERSITARIA, EDIF. ODEON, URB. LOS CHAGUARAMOS',
                'is_active' => true,
            ],
            [
                'user_id' => 1,
                'name' => 'JEXI BOLIVAR',
                'tax_id' => 'V-12096623-1',
                'contact_person' => 'Jexi Bolivar',
                'representative_cedula' => 'V-12096623-1',
                'email' => null,
                'phone' => '(0414) 183-67-59',
                'address' => 'No registrada',
                'fiscal_address' => 'No registrada',
                'is_active' => true,
            ],
            [
                'user_id' => 1,
                'name' => 'JOSE ANGEL VARGAS GALVIZ',
                'tax_id' => 'V-11930221-4',
                'contact_person' => 'Jose Angel Vargas Galviz',
                'representative_cedula' => 'V-11930221-4',
                'email' => null,
                'phone' => '(0414) 335-78-78',
                'address' => 'Qta. Maiveri, Urb. Piedra Azul, Caracas, Miranda',
                'fiscal_address' => 'Qta. Maiveri, Urb. Piedra Azul, Caracas, Miranda',
                'is_active' => true,
            ],
            [
                'user_id' => 1,
                'name' => 'JHONNY WILLIAN VIVAS ROSAS',
                'tax_id' => 'V-10633020-0',
                'contact_person' => 'Jhonny Willian Vivas Rosas',
                'representative_cedula' => 'V-10633020-0',
                'email' => null,
                'phone' => '(0424) 139-59-66',
                'address' => 'AV. INTERCOMUNAL DEL VALLE, URB. ZAMORA CARACAS, DISTRITO CAPITAL',
                'fiscal_address' => 'AV. INTERCOMUNAL DEL VALLE, URB. ZAMORA CARACAS, DISTRITO CAPITAL',
                'is_active' => true,
            ],
            [
                'user_id' => 1,
                'name' => 'LASEROFYS.C.A',
                'tax_id' => 'J-30966618-5',
                'contact_person' => null,
                'representative_cedula' => null,
                'email' => null,
                'phone' => '(0212) 614-57-88',
                'address' => 'AV. LIBERTADOR CON CALLE ELICE, EDIF. ARIZA, URB. CHACAO-CARACAS',
                'fiscal_address' => 'AV. LIBERTADOR CON CALLE ELICE, EDIF. ARIZA, URB. CHACAO-CARACAS',
                'is_active' => true,
            ],
            [
                'user_id' => 1,
                'name' => 'LABORATORIO GEMINIS, CA',
                'tax_id' => 'J-00124405-0',
                'contact_person' => null,
                'representative_cedula' => null,
                'email' => null,
                'phone' => '(0212) 261-33-93',
                'address' => 'EDIFICIO COSMOS, CHACAO, CARACAS',
                'fiscal_address' => 'EDIFICIO COSMOS, CHACAO, CARACAS',
                'is_active' => true,
            ],
            [
                'user_id' => 1,
                'name' => 'LUIS RAMON GARCIA GARCIA',
                'tax_id' => 'V-06139292-7',
                'contact_person' => 'Luis Ramon Garcia Garcia',
                'representative_cedula' => 'V-06139292-7',
                'email' => null,
                'phone' => '(0414) 299-34-92',
                'address' => 'AV. PRINCIPAL ALGODONAL, CALLE SIFON, BARRIO ALGODONAL CARACAS-DTTO. CAPITAL',
                'fiscal_address' => 'AV. PRINCIPAL ALGODONAL, CALLE SIFON, BARRIO ALGODONAL CARACAS-DTTO. CAPITAL',
                'is_active' => true,
            ],
            [
                'user_id' => 1,
                'name' => 'MIRNA DINHORA PRIETO ORTEGA',
                'tax_id' => 'V-12057067-2',
                'contact_person' => 'Mirna Dinhora Prieto Ortega',
                'representative_cedula' => 'V-12057067-2',
                'email' => null,
                'phone' => '(0414) 140-91-80',
                'address' => 'URB. EL MANICOMIO, CARACAS, DISTRITO CAPITAL',
                'fiscal_address' => 'URB. EL MANICOMIO, CARACAS, DISTRITO CAPITAL',
                'is_active' => true,
            ],
            [
                'user_id' => 1,
                'name' => 'MULTISERVICIOS LF 2050.C.A',
                'tax_id' => 'J-30778025-8',
                'contact_person' => null,
                'representative_cedula' => null,
                'email' => null,
                'phone' => '(0212) 443-81-55',
                'address' => 'AV.INTERCOMUNAL DE ANTIMANO, BARRIO EL SIFON, CARACAS-DTTO.CAPITAL',
                'fiscal_address' => 'AV.INTERCOMUNAL DE ANTIMANO, BARRIO EL SIFON, CARACAS-DTTO.CAPITAL',
                'is_active' => true,
            ],
            [
                'user_id' => 1,
                'name' => 'OXICAR TUY',
                'tax_id' => 'J-30396978-0',
                'contact_person' => null,
                'representative_cedula' => null,
                'email' => null,
                'phone' => '(0239) 248-17-62',
                'address' => 'Urb. Industrial Carabobo, Transversal 9, Calle 87 Valencia Edo. Carabobo',
                'fiscal_address' => 'Urb. Industrial Carabobo, Transversal 9, Calle 87 Valencia Edo. Carabobo',
                'is_active' => true,
            ],
            [
                'user_id' => 1,
                'name' => 'SUMINISTROS ALERE.C.A',
                'tax_id' => 'J-41143471-0',
                'contact_person' => null,
                'representative_cedula' => null,
                'email' => null,
                'phone' => '(0414) 298-28-25',
                'address' => 'AV. SOROCAIMA CON AV. FRANCISCO FAJARDO, EDIF. CENTRO SALUD. URB. SAN BERNARDINO, CARACAS DTTO. CAPITAL',
                'fiscal_address' => 'AV. SOROCAIMA CON AV. FRANCISCO FAJARDO, EDIF. CENTRO SALUD. URB. SAN BERNARDINO, CARACAS DTTO. CAPITAL',
                'is_active' => true,
            ],
            [
                'user_id' => 1,
                'name' => 'SUMINISTROS Y SERVICIOS CARMMY',
                'tax_id' => 'V-13577353-7',
                'contact_person' => 'Suministros y Servicios Carmmy',
                'representative_cedula' => 'V-13577353-7',
                'email' => null,
                'phone' => '(0414) 971-06-78',
                'address' => 'LA MONTAÑITA EJIDO, EDO. MERIDA, VENEZUELA',
                'fiscal_address' => 'LA MONTAÑITA EJIDO, EDO. MERIDA, VENEZUELA',
                'is_active' => true,
            ],
            [
                'user_id' => 1,
                'name' => 'BYOIMMUN 2000 C.A',
                'tax_id' => 'J-50417095-0',
                'contact_person' => null,
                'representative_cedula' => null,
                'email' => null,
                'phone' => '(0212) 515-43-91',
                'address' => 'AV. FCO DE MIRANDA, EDF. CAVENDES, URB ALTAMIRA',
                'fiscal_address' => 'AV. FCO DE MIRANDA, EDF. CAVENDES, URB ALTAMIRA',
                'is_active' => true,
            ],
            [
                'user_id' => 1,
                'name' => 'ONIX S.R.L GRAFICAS',
                'tax_id' => 'J-00326937-9',
                'contact_person' => null,
                'representative_cedula' => null,
                'email' => null,
                'phone' => '(0212) 552-75-32',
                'address' => 'AVENIDA CAJIGAL, QUINTA DALIA, SAN BERNARDINO',
                'fiscal_address' => 'AVENIDA CAJIGAL, QUINTA DALIA, SAN BERNARDINO',
                'is_active' => true,
            ],
            [
                'user_id' => 1,
                'name' => 'SUPLIDORES BIOTEC',
                'tax_id' => 'J-00353790-0',
                'contact_person' => null,
                'representative_cedula' => null,
                'email' => null,
                'phone' => '(0212) 234-47-89',
                'address' => 'CALLE SANTA ANA, EDIF. CENTRO EMPRESARIAL BOLEITA, URB. BOLEITA, CARACAS',
                'fiscal_address' => 'CALLE SANTA ANA, EDIF. CENTRO EMPRESARIAL BOLEITA, URB. BOLEITA, CARACAS',
                'is_active' => true,
            ],
            [
                'user_id' => 1,
                'name' => 'LABOMED',
                'tax_id' => 'J-00115702-6',
                'contact_person' => null,
                'representative_cedula' => null,
                'email' => null,
                'phone' => '(0212) 690-14-22',
                'address' => 'CALLE LOS MALABARES, GALPON N 29, URB. LOS ROSALES. CARACAS',
                'fiscal_address' => 'CALLE LOS MALABARES, GALPON N 29, URB. LOS ROSALES. CARACAS',
                'is_active' => true,
            ],
            [
                'user_id' => 1,
                'name' => 'SIMONCAS 3130 CA',
                'tax_id' => 'J-41045539-0',
                'contact_person' => null,
                'representative_cedula' => null,
                'email' => null,
                'phone' => '(0424) 142-43-65',
                'address' => 'BARRIO SUCRE, CARACAS D.C',
                'fiscal_address' => 'BARRIO SUCRE, CARACAS D.C',
                'is_active' => true,
            ],
        ];

        DB::table('suppliers')->insert($suppliers);
    }
}